# Generated by Django 6.0.3 on 2026-03-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        help_text="ISO 4217 numeric code", unique=True
                    ),
                ),
                ("iso_code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("is_monitored", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="RateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_rate", models.DecimalField(decimal_places=4, max_digits=12)),
                ("sell_rate", models.DecimalField(decimal_places=4, max_digits=12)),
                ("added_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate History",
                "verbose_name_plural": "Rate Histories",
                "ordering": ["-added_at"],
            },
        ),
    ]
