# Generated by Django 6.0.3 on 2026-03-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="currency",
            table="currencies",
        ),
    ]
