# Generated by Django 6.0.3 on 2026-03-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_alter_currency_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="iso_code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
